export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const LOAD_EVENTS_REQUEST = 'LOAD_EVENTS_REQUEST';

export const LOAD_SINGLE_EVENT_SUCCESS = 'LOAD_SINGLE_EVENT_SUCCESS';
export const LOAD_SINGLE_EVENT_REQUEST = 'LOAD_SINGLE_EVENT_REQUEST';

export const LOAD_COMBINED_SUCCESS = 'LOAD_COMBINED_SUCCESS';
export const LOAD_COMBINED_REQUEST = 'LOAD_COMBINED_REQUEST';
export const LOAD_COMBINED_FAILURE = 'LOAD_COMBINED_FAILURE';

export const LOAD_PUBLIC_DOSSIERS_SUCCESS = 'LOAD_PUBLIC_DOSSIERS_SUCCESS';
export const LOAD_PUBLIC_DOSSIERS_REQUEST = 'LOAD_PUBLIC_DOSSIERS_REQUEST';

export const LOAD_PUBLIC_DOSSIER_SUCCESS = 'LOAD_PUBLIC_DOSSIER_SUCCESS';
export const LOAD_PUBLIC_DOSSIER_REQUEST = 'LOAD_PUBLIC_DOSSIER_REQUEST';

export const LOAD_LATEST_DATA_SUCCESS = 'LOAD_LATEST_DATA_SUCCESS';
export const LOAD_LATEST_DATA_REQUEST = 'LOAD_LATEST_DATA_REQUEST';
export const CLEAR_LATEST_DATA = 'CLEAR_LATEST_DATA';

export const ADD_FILTER_SUCCESS = 'ADD_FILTER_SUCCESS';
export const REMOVE_FILTER_SUCCESS = 'REMOVE_FILTER_SUCCESS';
export const REMOVE_ALL_FILTER_SUCCESS = 'REMOVE_ALL_FILTER_SUCCESS';
export const SET_SORT_BY_SUCCESS = 'SET_SORT_BY_SUCCESS';
export const SET_ACTIVE_PAGE_SUCCESS = 'SET_ACTIVE_PAGE_SUCCESS';
export const SET_ACTIVE_TAB_SUCCESS = 'SET_ACTIVE_TAB_SUCCESS';
export const SET_FILTER_SUCCESS = 'SET_FILTER_SUCCESS';
export const HANDLE_ACTION_MENU_CLICK_SUCCESS = 'HANDLE_ACTION_MENU_CLICK_SUCCESS';
export const SET_QUERY_MODAL_SUCCESS = 'SET_QUERY_MODAL_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';

export const SET_SNACKBAR_SUCCESS = 'SET_SNACKBAR_SUCCESS';
export const SET_DOSSIER_MODAL_SUCCESS = 'SET_DOSSIER_MODAL_SUCCESS';

export const LOAD_FAVORITE_REQUEST = 'LOAD_FAVORITE_REQUEST';
export const LOAD_FAVORITE_SUCCESS = 'LOAD_FAVORITE_SUCCESS';

export const LOAD_USER_DOSSIERS_SUCCESS = 'LOAD_USER_DOSSIERS_SUCCESS';
export const LOAD_USER_DOSSIERS_REQUEST = 'LOAD_USER_DOSSIERS_REQUEST';

export const LOAD_DOSSIER_CONTENT_SUCCESS = 'LOAD_DOSSIER_CONTENT_SUCCESS';
export const LOAD_DOSSIER_CONTENT_REQUEST = 'LOAD_DOSSIER_CONTENT_REQUEST';

export const LOAD_USER_QUERIES_SUCCESS = 'LOAD_USER_QUERIES_SUCCESS';
export const LOAD_USER_QUERIES_REQUEST = 'LOAD_USER_QUERIES_REQUEST';

export const EDIT_PROFILE_DATA_SUCCESS = 'EDIT_PROFILE_DATA_SUCCESS';
export const EDIT_PROFILE_DATA_REQUEST = 'EDIT_PROFILE_DATA_REQUEST';

export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST';

export const SET_SAVED_QUERY = 'SET_SAVED_QUERY';

export const SET_ADD_NOTE_SUCCESS = 'SET_ADD_NOTE_SUCCESS';

export const LOAD_MY_NOTES_SUCCESS = 'LOAD_MY_NOTES_SUCCESS';
export const LOAD_MY_NOTES_REQUEST = 'LOAD_MY_NOTES_REQUEST';

export const GENERAL_REQUEST_FAILED = 'GENERAL_REQUEST_FAILED';
export const GENERAL_REQUEST = 'GENERAL_REQUEST';

export const LOAD_MY_AGENDAS_SUCCESS = 'LOAD_MY_AGENDAS_SUCCESS';

export const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS';
export const LOAD_NOTIFICATIONS_REQUEST = 'LOAD_NOTIFICATIONS_REQUEST';

export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';

export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';

export const SET_SELECTED_COMBINED_ITEM_ID = 'SET_SELECTED_COMBINED_ITEM_ID';

export const REMOVE_SELECTED_COMBINED_ITEM_ID = 'REMOVE_SELECTED_COMBINED_ITEM_ID';

export const LOAD_EVENT_SPEAKERS_SUCCESS = 'LOAD_EVENT_SPEAKERS_SUCCESS';
export const LOAD_EVENT_SPEAKERS_REQUEST = 'LOAD_EVENT_SPEAKERS_REQUEST';

export const SAVE_CALENDAR_DATE = 'SAVE_CALENDAR_DATE';
export const CLEAR_CALENDAR_DATE = 'CLEAR_CALENDAR_DATE';

export const SPECIFY_SEARCH = 'SPECIFY_SEARCH';

export const FROM_PASSWORD_RESET = 'FROM_PASSWORD_RESET';

// PUBLISHER //
export const ADD_USER_MODAL_SUCCESS = 'ADD_USER_MODAL_SUCCESS';

export const SET_PUBLIC_DOSSIER_MODAL_SUCCESS = 'SET_PUBLIC_DOSSIER_MODAL_SUCCESS';
export const SET_SELECTED_DOCUMENTS = 'SET_SELECTED_DOCUMENTS';
export const SET_SELECTED_DOSSIERS = 'SET_SELECTED_DOSSIERS';
export const CLEAR_PUBLIC_DOSSIER_MODAL_DATA = 'CLEAR_PUBLIC_DOSSIER_MODAL_DATA';

export const SET_NEW_EVENT_SUCCESS = 'SET_NEW_EVENT_SUCCESS';
export const CLEAR_EVENT_MODAL_DATA = 'CLEAR_EVENT_MODAL_DATA';

export const SET_EVENT_DOCUMENT_MODAL_SUCCESS = 'SET_EVENT_DOCUMENT_MODAL_SUCCESS';
export const CLEAR_EVENT_DOCUMENT_MODAL_DATA = 'CLEAR_EVENT_DOCUMENT_MODAL_DATA';
export const SET_EVENT_DOCUMENTS = 'SET_EVENT_DOCUMENTS';

export const SET_NEW_AGENDA_ITEM_SUCCESS = 'SET_NEW_AGENDA_ITEM_SUCCESS';
export const CLEAR_AGENDA_ITEM_MODAL_DATA = 'CLEAR_AGENDA_ITEM_MODAL_DATA';
export const SET_AGENDA_ITEM_SELECTED_DOCUMENTS = 'SET_AGENDA_ITEM_SELECTED_DOCUMENTS';
export const SET_AGENDA_ITEM_DOSSIERS = 'SET_AGENDA_ITEM_DOSSIERS';

export const SET_DOCUMENT_MODAL_SUCCESS = 'SET_DOCUMENT_MODAL_SUCCESS';
