const data = {
  id: 3451,
  notubiz_id: 519944,
  name: 'Commissie tot Onderzoek van de Rekening (2018-2022) Hoorzitting wethouder Visser',
  description: 'n/a',
  jurisdiction: 'Gemeente Rotterdam',
  start_time: '2018-05-18T09:30:00',
  classification: 'Commissie tot Onderzoek van de Rekening (2018-2022)',
  location: 'Stadhuis, zaal SH 7',
  parent_event: null,
  last_modified: '2018-05-18T10:47:52',
  documents: [
    {
      id: 101180,
      ibabs_id: null,
      combined_id: 102620,
      text: '2018 COR Vragen voor wethouderVisser inzake jaarrekening2017',
      attached_to: 'agenda_item',
      url: 'https://api.notubiz.nl/document/6457560/1',
      media_type: '',
      notes: [],
      event: 3451,
      date: '2018-05-18T10:47:53',
      document_content_text: '',
    },
  ],
  event_media: [
    {
      id: 1344,
      filename: 'S_18.05.2018_NC_Rotterdam_Rekening.mp4',
      httpstream:
        'http://wowza1.notubiz.nl/nbvod/_definst_/Rotterdam/bestanden/S_18.05.2018_NC_Rotterdam_Rekening.mp4/playlist.m3u8',
      rtmpstream:
        'rtmp://wowza1.notubiz.nl/nbvod/_definst_/Rotterdam/bestanden/S_18.05.2018_NC_Rotterdam_Rekening.mp4',
      download:
        'rotterdam.raadsinformatie.nl/media/download?file=S_18.05.2018_NC_Rotterdam_Rekening.mp4',
      event: 3451,
    },
  ],
  agenda: [
    {
      id: 38417,
      notes: 'Opening en mededelingen',
      description: '',
      start_time: null,
      end_time: null,
      order: 1,
      classification: null,
      event: 3451,
      media: [],
    },
    {
      id: 38418,
      notes:
        'Vragen van de Commissie tot Onderzoek van de Rekening - hoorzitting met wethouder Visser inzake jaarrekening 2017',
      description: '',
      start_time: null,
      end_time: null,
      order: 2,
      classification: null,
      event: 3451,
      media: [
        {
          id: 94718,
          note: '2018 COR Vragen voor wethouderVisser inzake jaarrekening2017',
          date: '2018-05-18T09:30:00',
          agenda_item: 38418,
          links: [
            {
              id: 94718,
              combined_id: 102620,
              doc_id: 101180,
              url: 'https://api.notubiz.nl/document/6457560/1',
              media_type: '',
              text: '2018 COR Vragen voor wethouderVisser inzake jaarrekening2017',
              media: 94718,
            },
          ],
        },
      ],
    },
    {
      id: 38419,
      notes: 'Sluiting',
      description: '',
      start_time: null,
      end_time: null,
      order: 3,
      classification: null,
      event: 3451,
      media: [],
    },
    {
      id: 38153,
      notes: 'Opening en mededelingen',
      description: '',
      start_time: null,
      end_time: null,
      order: null,
      classification: null,
      event: 3451,
      media: [],
    },
    {
      id: 38154,
      notes:
        'Vragen van de Commissie tot Onderzoek van de Rekening - hoorzitting met wethouder Visser inzake jaarrekening 2017',
      description: '',
      start_time: null,
      end_time: null,
      order: null,
      classification: null,
      event: 3451,
      media: [
        {
          id: 93952,
          note: '2018 COR Vragen voor wethouderVisser inzake jaarrekening2017',
          date: '2018-05-18T09:30:00',
          agenda_item: 38154,
          links: [
            {
              id: 93952,
              combined_id: 102620,
              doc_id: 101180,
              url: 'https://api.notubiz.nl/document/6457560/1',
              media_type: '',
              text: '2018 COR Vragen voor wethouderVisser inzake jaarrekening2017',
              media: 93952,
            },
          ],
        },
      ],
    },
    {
      id: 38155,
      notes: 'Sluiting',
      description: '',
      start_time: null,
      end_time: null,
      order: null,
      classification: null,
      event: 3451,
      media: [],
    },
  ],
  document_count: 1,
  agenda_count: 6,
  media_count: 1,
  combined_id: 102619,
};
