const data = {
  count: 3,
  next: null,
  previous: null,
  results: [
    {
      id: 429,
      title: 'asdasdsa',
      accessibility: 'Private',
      color: '#aa0021',
      created_at: '2018-05-14T10:48:07.428763',
      last_modified: '2018-05-14T10:48:07.428798',
      is_verified: false,
      ordering_id: null,
      owner: {
        id: 10,
        username: 'Martizs',
        profile_pic: 'media/profile_pictures/default_pic.png',
        email: 'elbartas321@gmail.com',
        first_name: 'Martizs',
        last_name: 'Martizs',
      },
      shared_users: [],
    },
    {
      id: 425,
      title: 'test',
      accessibility: 'Private',
      color: '#fd0012',
      created_at: '2018-05-08T10:20:50.577129',
      last_modified: '2018-05-08T10:20:50.577175',
      is_verified: false,
      ordering_id: null,
      owner: {
        id: 10,
        username: 'Martizs',
        profile_pic: 'media/profile_pictures/default_pic.png',
        email: 'elbartas321@gmail.com',
        first_name: 'Martizs',
        last_name: 'Martizs',
      },
      shared_users: [],
    },
    {
      id: 428,
      title: 'New Folder lol',
      accessibility: 'Private',
      color: '#ff1493',
      created_at: '2018-05-14T08:21:41.557119',
      last_modified: '2018-05-14T08:21:41.557157',
      is_verified: false,
      ordering_id: null,
      owner: {
        id: 10,
        username: 'Martizs',
        profile_pic: 'media/profile_pictures/default_pic.png',
        email: 'elbartas321@gmail.com',
        first_name: 'Martizs',
        last_name: 'Martizs',
      },
      shared_users: [],
    },
  ],
};
